#: include kv/LoginScreen.kv
#: include kv/RegisterScreen.kv
#: include kv/MainMenuScreen.kv
#: include kv/InputScreen.kv
#: include kv/EditScreen.kv

ScreenManager:
    id: screen_manager
    LoginScreen:
        id: loginscreen
    MainMenuScreen:
        id: mainmenuscreen
    RegisterScreen:
        id: registerscreen
    InputScreen:
        id: inputscreen
    EditScreen:
        id: editscreen